upstream api { server api:3001; }
upstream auth { server auth:4001; }
upstream delivery { server delivery:8086; }
upstream search { server search:4004; }
upstream notifications { server notifications:4007; }
upstream forums { server forum:8087; }
upstream emergency { server emergency:8088; }
upstream gov { server gov:8089; }
upstream rides { server ride-hailing:8085; }
upstream storage { server storage:3011; }
upstream chat { server chat:3013; }

server {
    listen 80;

    location /auth { proxy_pass http://auth; }
    location /delivery { proxy_pass http://delivery; }
    location /search { proxy_pass http://search; }
    location /notifications { proxy_pass http://notifications; }
    location /forums { proxy_pass http://forums; }
    location /emergency { proxy_pass http://emergency; }
    location /gov { proxy_pass http://gov; }
    location /rides { proxy_pass http://rides; }
    location /storage { proxy_pass http://storage; }
    location /chat {
        proxy_pass http://chat:3013;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
    location / { proxy_pass http://api; }
}
