events {
    worker_connections 1024;
}

http {
    upstream api { server api:3001; }
    upstream auth { server auth:4001; }
    upstream delivery { server delivery:8086; }
    upstream notifications { server notifications:4007; }

    server {
        listen 80;

        location /auth { proxy_pass http://auth; }
        location /delivery { proxy_pass http://delivery; }
        location /notifications { proxy_pass http://notifications; }
        location / { proxy_pass http://api; }
    }
}
