import { prisma } from '@doorli/db';
import { AppError } from '../../middleware/errorHandler.js';

/** Generate a simple hall booking contract and attach to the booking. */
export async function generateHallContract(bookingId: string): Promise<{ contractText: string; bookingId: string; contractUrl: string }> {
  const booking = await prisma.booking.findUnique({
    where: { id: bookingId },
    include: { vendor: true, customer: true },
  });
  if (!booking) throw new AppError(404, 'Booking not found');
  if (booking.bookingType !== 'hall') throw new AppError(400, 'Not a hall booking');

  const contractText = [
    'DOORLI HALL BOOKING CONTRACT',
    `Booking #: ${booking.bookingNumber}`,
    `Venue: ${booking.vendor.businessName}`,
    `Customer: ${booking.customer.fullName} (${booking.customer.phone})`,
    `Event date: ${booking.eventDate?.toISOString().slice(0, 10) ?? 'TBD'}`,
    `Guests: ${booking.guestCount ?? 'N/A'}`,
    `Total: LKR ${booking.totalAmount}`,
    `Deposit: LKR ${booking.depositAmount ?? 0}`,
    '',
    'Terms: Deposit is non-refundable within 7 days of the event.',
    'Generated by Doorli platform.',
  ].join('\n');

  const contractUrl = `contract://${booking.id}`;
  await prisma.booking.update({
    where: { id: bookingId },
    data: {
      contractUrl,
      requirements: `${booking.requirements ?? ''}\n\n${contractText}`.trim(),
    },
  });

  return { contractText, bookingId, contractUrl };
}
