import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#e5e2e1",
        "primary-fixed": "#ffdad8",
        "tertiary-container": "#30a193",
        "surface-container-low": "#1c1b1b",
        "on-secondary-fixed-variant": "#064c6b",
        "surface-container-lowest": "#0e0e0e",
        "surface-dim": "#131313",
        "tertiary-fixed": "#8cf5e4",
        "on-error": "#690005",
        background: "#121212",
        "primary-fixed-dim": "#ffb3b1",
        "surface-bright": "#393939",
        "surface-container-high": "#2a2a2a",
        "on-secondary": "#00344c",
        "on-tertiary-fixed": "#00201c",
        "on-primary-container": "#5b000e",
        "surface-variant": "#353534",
        "on-secondary-container": "#8abfe4",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#005048",
        "outline-variant": "#5b403f",
        "secondary-fixed": "#c7e7ff",
        "tertiary-fixed-dim": "#6fd8c8",
        "on-surface": "#e5e2e1",
        "secondary-fixed-dim": "#98cdf2",
        "inverse-on-surface": "#313030",
        "on-secondary-fixed": "#001e2e",
        "surface-container": "#201f1f",
        "primary-container": "#ff535b",
        "on-error-container": "#ffdad6",
        "secondary-container": "#0b4e6e",
        tertiary: "#6fd8c8",
        "on-primary-fixed-variant": "#92001c",
        "surface-tint": "#ffb3b1",
        primary: "#ffb3b1",
        "on-primary": "#680011",
        "on-surface-variant": "#e4bebc",
        "surface-container-highest": "#353534",
        "inverse-primary": "#bb152c",
        surface: "#131313",
        "on-tertiary": "#003731",
        outline: "#ab8987",
        "on-tertiary-container": "#00302a",
        "on-background": "#e5e2e1",
        "on-primary-fixed": "#410007",
        error: "#ffb4ab",
        secondary: "#98cdf2",
        "doorli-red": "#E63946",
        muted: "#A0A0A0",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "32px",
        sm: "8px",
        "container-max": "1440px",
        lg: "24px",
        gutter: "16px",
        xs: "4px",
        "margin-mobile": "16px",
        md: "16px",
        "margin-desktop": "24px",
        base: "4px",
      },
      fontFamily: {
        "body-compact": ["Inter", "sans-serif"],
        "screen-title": ["Inter", "sans-serif"],
        "body-main": ["Inter", "sans-serif"],
        "section-header": ["Inter", "sans-serif"],
        "label-medium": ["Inter", "sans-serif"],
        "screen-title-mobile": ["Inter", "sans-serif"],
        "kpi-number": ["Inter", "sans-serif"],
        caption: ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-compact": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "screen-title": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-main": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "section-header": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "label-medium": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "screen-title-mobile": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "kpi-number": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        caption: [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
      },
    },
  },
  plugins: [],
};
export default config;
